package com.jsp.wms.enums;

public enum Privileges {
	CREATE_WAREHOUSE,
	CREATE_ADMIN,
	CREATE_ADDRESS,
	CREATE_STORAGE,
	READ,
	UPDATE_ADMIN,
	UPDATE_WAREHOUSE,
	UPDATE_ADDRESS,
	UPDATE_STORAGE,
	DELETE_ADMIN,
	DELETE_WAREHOUSE,
	DELETE_ADDRESS,
	DELETE_STORAGE

}
